apiVersion: v1
kind: Service
metadata:
  name: rest-on-kubernetes-service
spec:
  ports:
  - port: 30001
    nodePort: 30001
    targetPort: rok-port
    protocol: TCP
  selector:
    app: rest-on-kubernetes
  type: NodePort

